bruno/Seestar Alpaca API/Schedule - Mosaic/action-add_schedule_item_exp_time.bru
I added this item based on the other items and files.
=> Item to change the exposure time in the Scheduler

.dockerignore, .gitignore, docker/Dockerfile, docker/README.md, docker/config.toml.example, docker/entrypoint.sh, docker/run.sh, docker/util.sh
This PR adds support for running seestar_alp in a docker container.  This should make it easy to run on any OS and architecture.  If you're interested, I could also setup GitHub actions to build and upload images so that people can just download and run, but it's also not hard to build.
=> Add support for running in docker.

device/config.toml, device/seestar_device.py
Retries on connect and comments in config.toml
=> Add retry when attempting to connect to seestar

README.md, front/ROADMAP.md
Also added UI roadmap / wishlist.
=> Updating README to include instructions for UI.

front/ROADMAP.md, front/app.py, front/templates/clear_schedule.html, front/templates/image.html, front/templates/image_create.html, front/templates/index.html, front/templates/mosaic_create.html, front/templates/nav.html, front/templates/schedule.html, front/templates/schedule_list.html, front/templates/schedule_shutdown.html
- Display stats on home page
- Single shot photo, schedule photo pages
- Clear schedule button
- Verbiage fix
=> UI enhancements

device/seestar_device.py, device/telescope.py
The retry logic in seestar_device was cleaned up.
Restart logic was added if shutdown has been sent
In telescope.py,  moveaxis had a small bug
=> Clean up Retry logic

front/ROADMAP.md, front/app.py, front/templates/base.html, front/templates/index.html, front/templates/mosaic_create.html, front/templates/schedule_list.html, front/templates/stats.html
The GUI was ported from Flask to the Falcon framework.
Some GUI validation was added for RA and Dec.
=> Porting frontend to Falcon framework, adding some validation

front/app.py
Fixes regexp list for RA check to support -1.  Also adds -1.0 variant.
Closes #38
=> fixing RA check for -1

Raspberry Pi Install.md
Basic notes for Raspberry Pi Install
=> Create Raspberry Pi Install.md

front/app.py, front/templates/do_command.html
Add dew heater (on/off) to commands page.
=> Dew heater commands

device/config.py, device/config.toml, front/app.py, front/public/main.js, front/templates/image_create.html, front/templates/mosaic_create.html
Allow various ways to fill in RA/Dec, from Simbad, from Stellarium, and from Clipboard.
=> Retreive RA/Dec

Raspberry Pi Install.md, systemd/README.txt, systemd/seestar_device.service, systemd/seestar_front.service
Add example systemd service files, and instructions on how to install
=> Add systemd service files

raspberry_pi/setup.sh
Rpi setup: Add back line dropped in last commit
=> Rpi setup: Add back line dropped

front/app.py
Print to console the IP:Port the front/app.py has started on.
=> Print IP:Port of SSC (WebUI)

bruno/Seestar Alpaca API/Schedule - Mosaic/action-add_schedule_item_mosaic.bru, bruno/Seestar Alpaca API/Schedule - Mosaic/action-add_schedule_item_mosaic_j2000.bru, bruno/Seestar Alpaca API/Schedule - Mosaic/action-start_mosaic.bru, bruno/Seestar Alpaca API/Schedule - Mosaic/action-start_mosaic_j2000.bru
Updated Bruno collection to add is_use_autofocus parameter to the 4 mosaic entries under Schedule - Mosaic
=> Updated Bruno collection to add is_use_autofocus parameter

front/public/main.js
Simbad lookup returns j2000 ra/dec, we should check the checkbox for j2000 on the page.
=> When using Simbad lookup check the j2000 checkbox

front/app.py, front/templates/clear_schedule.html
Adds schedule import and export functionality.   (Schedule is saved / restored from a CSV file.)
Works in both online and offline modes.
=> Import and export schedule

front/app.py
Some combinations of scheduled jobs would not work on the round trip of export / import.   This should fix the issue.
=> Fixing certain combinations of scheduled jobs with import / export

front/app.py, front/templates/command.html, front/templates/image.html, front/templates/index.html, front/templates/mosaic.html, front/templates/schedule_base.html, front/templates/schedule_list.html, front/templates/stats.html, front/templates/telescope_list.html
Updated html templates to be uniform and use bootstrap grid instead of tables.
=> Markup enhancements

front/app.py, front/templates/nav.html, front/templates/settings.html, raspberry_pi/setup.sh
=> Added Settings Page

device/app.py, device/log.py, front/app.py, root_app.py
Restructured code to support running through new unified root_app, but also standalone.
Converting a log of "print" statements to logging statements.
Adding new endpoints (not hooked up to frontend) allowing frontend to startup and shutdown "device/app".
=> Restructuring code to support unification of "front/app" and "device/app"

front/app.py
Fixed render_settings to check for online status before sending get_device_settings()
=> Fixed render_settings to check for online status before sending get_device_settings()

front/app.py, raspberry_pi/setup_unified.sh, raspberry_pi/systemd/seestar_unified.service
Disable IPv6 on requests which was causing incredible slowness on Windows computers.  (I didn't realize it was as bad as it was.)
WIP: Added setup script for unified app on Raspberry Pis.
=> Fix for IPv6 slowness on Windows.  Added unified Raspberry Pi script.

front/app.py, front/templates/do_command.html
Remove dew heater on/off from commands page. Dew heater on/off is now in the settings page.
=> Remove dew heater from commands page.

front/templates/command.html
If offline, don't show "Select a command to execute".
=> Minor command page fix. 

device/seestar_device.py, front/app.py, front/templates/schedule_base.html, front/templates/schedule_list.html
- When scheduler is running, the currently running item is highlighted
- Scheduler status and schedule are dynamically updated every 2 seconds
Closes #94
=> Highlight currently running schedule item; dynamically update scheduler status

front/templates/schedule_base.html, front/templates/schedule_list.html
[move clear, import, export buttons out of schedule_list](https://github.com/smart-underworld/seestar_alp/commit/4f88e5aba07b76c2e63da58fd3610455fe5ed8c5)
=> move clear, import, export buttons out of schedule_list

front/templates/schedule_base.html
=> Fixed id of twilight collapse.

device/config.py, device/config.toml.example, front/app.py, front/public/main.js
If you fetch info from Simbad or Stellarium it will turn on the LP Filter if object is of type HII, ISM, SNR, or PN.
Created new config.toml entry for stellarium host.  sthost.  You can now put Stellarium on a different machine. Defaults to localhost.
=> Auto LP Filter and stellarium hostname

device/config.py, device/config.toml.example, front/app.py, front/templates/schedule_base.html, front/templates/settings.html
Added:
- Config file twilight times enable/disable option, default disabled. 
- Global detect internet function. (Hopefully helpful for other areas) 
- Twilight Times now works without an internet connection. 
- Twilight Times now caches daily results.
- Twilight Time the user can now update lat/lon.
Changed:
- Minor update to ToggleUITheme, changed class name to be more consistent with the rest of the class names.
=> Twilight Times Logic Updates

root_app.py
Check pip dependencies at startup before launching the root app
=> Check pip dependencies at startup

front/app.py, front/public/main.js, front/templates/schedule_base.html
Added request location button. (This will try to lookup your location via IP)
Some code cleanup as well.
=> Twilight times: Added request location button.

docker/README.md, docker/config.toml.example
Updated readme to include instructions on using INDI server with Stellarium,
Updated config.toml.example to reflect recent changes to front end.
=> Updated readme and config.toml example

README.md
Reverts smart-underworld/seestar_alp#136
=> Revert "Top level README.md consistency"

mac/tools/capture_tcpdump.sh
Add a tool for the mac, to capture a tcpdump from an iOS device interaction
=> Add a tool for the mac, to capture a tcpdump from an iOS device interaction

device/app.py, device/seestar_device.py, device/seestar_imaging.py, front/app.py, front/templates/live_status.html, root_app.py
FIX: changed imports to what they were before.  The structure of these imports needs to be revisited.  (The reason they're problematic has to do with how Python deals with "globals" in namespaces.  I think.)
UPDATE: moved some logging entries from "info" to "debug" to reduce chatter in logs
UPDATE: changed some thread names to distinguish device from imaging threads
Also removed some unused code.
=> Fixing imports; adjusting logging and thread names

front/app.py, front/templates/nav.html
Dark mode is now a toggle switch and is more mobile friendly.
=> Dark mode is now a toggle switch

device/seestar_device.py, front/app.py, front/templates/partials/schedule_tab_header.html, front/templates/schedule.html, front/templates/schedule_list.html
Because the 2.0 app doesn't do this properly - make it a task able to be scheduled.
=> Make LPF a schedulable item

front/app.py, front/templates/base.html, front/templates/live.html, front/templates/nav.html
Add preliminary telescope movement controls to live view.
Experimenting with live view layout.  On larger screens, status and controls to right of image.  On smaller screens, previous vertical layout.
=> add telescope movement controls to live view

front/app.py
- Fixed unable to add image/mosaic to schedule while in offline mode.
- Fixed automatic offline -> online of scheduled items.
=> Offline scheduler fixes.

front/templates/command.html, front/templates/image.html, front/templates/live.html, front/templates/mosaic.html, front/templates/settings.html, front/templates/stats.html
- The "Go Online" button is not longer needed as online/offline should be automatic.
- Added online/offline detection to live view page.
=> Removed "Go Online" button.

front/templates/schedule_list.html
=> Remove "Go Online" button

front/app.py
- Don't show free space while in USB storage mode.
=> Stats: Detect when in USB storage mode.

device/config.py, device/config.toml.example, device/seestar_imaging.py, device/shr.py, front/app.py, front/templates/live.html, front/templates/live_status.html
- Improvement: track current view mode more systematically to correctly show right highlighted button in Live View mode
- Chore: changed web logging from INFO to DEBUG
- Fix: updated default imgport from 5556 to 7556 to work around conflict with plugin on Windows!
- Fix: made timeouts more consistent
=> Move more logging to DEBUG, change default imgport, track liveview img mode

device/config.py, device/config.toml.example, device/seestar_device.py, device/shr.py
optimize logging to  put verbose heartbeat related commands in debug allow a logging flag to determine how to display events
=> Support both directions for rotation for start-up sequence

scripts/manual-mosaic.py
Example execution:
```
bguthro@ben-MacBook-Pro dev % ./seestar_alp/scripts/manual-mosaic.py --target_name CirrusLoop --nRA 5 --nDec 3 --center_RA 20h51m29.31s --center_Dec=+30d40m30.9s --time_in_hours=7 --use_LP 
action,local_time,timer_sec,try_count,target_name,is_j2000,ra,dec,is_use_lp_filter,session_time_sec,ra_num,dec_num,panel_overlap_percent,gain,is_use_autofocus,heater,nokey
start_mosaic,,,,CirrusLoop_11,False,20.766094732071583,29.643250000000002,True,1680,1,1,100,80,False,False,
start_mosaic,,,,CirrusLoop_21,False,20.812118199369124,29.643250000000002,True,1680,1,1,100,80,False,False, 
start_mosaic,,,,CirrusLoop_31,False,20.858141666666665,29.643250000000002,True,1680,1,1,100,80,False,False, 
start_mosaic,,,,CirrusLoop_41,False,20.904165133964206,29.643250000000002,True,1680,1,1,1 …
```
=> Add script for manual mosaic panels

scripts/mosaic-stats.py
Switched to use pathlib to generate paths that work for Windows/MacOS/Linux.
Tested on Windows & Linux. @bguthro please test on MacOS
=> Made the mosaic-stats script OS agnostic for paths

front/app.py, scripts/mosaic-stats.py
Added Target Name, Successful Frames & Failed Frames to the stats page.
=> Address Issue #222

device/discovery.py, device/rotator.py, device/seestar_device.py, device/seestar_util.py, device/telescope.py, front/app.py, lint/lint.sh, lint/pylintrc, requirements.txt, root_app.py
This adds a python linter to the project, but does not resolve the errors detected.
=> Add python linter script, and fix problems it reported.

front/app.py, front/templates/image_create.html, front/templates/mosaic_create.html
Convert HMS to seconds for image/mosaic pages.
=> HMS to secs for image/mosaic

front/app.py
Addressed issue in get_device_state where if view_state was not working it'd crash on the main/stats page of SSC
=> Correct issue with get_device_state

front/app.py
Removed unneeded else statements.
=> One last bit of cleanup in get_device_state

front/app.py, front/templates/do_command.html
Updated to add support for lat/long parameters to the action_start_up_sequence command on the SSC commands page.
=> Update action_start_up_sequence in commands form

front/app.py, front/templates/do_command.html
Updated Commands Page to add start/stop_create_dark and start/stop_polar_align.
=> Added create darks & polar align commands to SSC

front/app.py, front/templates/nav.html, front/templates/support.html
Add a page with a problem description field, and a "download bundle" button
=> Add support page

front/app.py, front/templates/do_command.html
Added some sanitizing using strip() to data from the form post.
Added 18 new commands under "Get Information / Settings" on the commands page.
=> Fixed issue with command page. Added additional commands

front/app.py, front/public/main.js, front/templates/goto.html, front/templates/goto_target.html, front/templates/nav.html
Added a Goto Page to SSC.  Allow users to go to a target and not start imaging.
=> Add Goto Page to SSC

device/app.py, device/seestar_logs.py, device/telescope.py, front/app.py
This adds a `seestar_1_logs.zip` file to the support bundle, that it collects from the telescope on port 4801
=> Add ability to collect telescope logs as part of support bundle

front/app.py
Image now immediately starts instead of getting added to schedule.
=> Fixed issue with image page.

front/app.py, front/templates/do_command.html
Fixed a couple of commands and typos.
=> Fixed a few small issues on the command page

front/app.py, front/templates/do_command.html
Updated support page to have OS agnostic code.
Removed a couple of unneeded commands from the command page.
=> Updates to support page

.github/workflows/build_seestar_alp.yaml, device/version.py, front/app.py, front/templates/command.html, front/templates/goto.html, front/templates/image.html, front/templates/index.html, front/templates/live.html, front/templates/live_mode.html, front/templates/mosaic.html, front/templates/schedule_base.html, front/templates/settings.html, front/templates/stats.html, front/templates/support.html, front/templates/system.html, raspberry_pi/setup.sh, raspberry_pi/systemd/seestar.service, raspberry_pi/update.sh
Include the version in a footer of all pages
=> Include version in UI

front/app.py, front/templates/nav.html
Initial implementation of Seestar Federation in SSC. 
To use Federation, select 'Seestar Federation' from the drop-down.
The pages where Federation works are Commands, Goto, Mosaic, Schedule & Settings.
=> Initial Seestar Federation integration in SSC

front/app.py, front/templates/nav.html
Reverts smart-underworld/seestar_alp#257
=> Revert "Initial Seestar Federation integration in SSC"

front/app.py, front/public/main.js, front/templates/goto_target.html, front/templates/image_create.html, front/templates/mosaic_create.html, requirements.txt
Used Skyfield to do planetary coordinate lookups along with edits to related javascript, templates and requirements.txt.
=> Added planetary coordinate lookups

front/app.py, front/templates/mosaic_create.html, front/templates/nav.html, front/templates/partials/schedule_tab_header.html, front/templates/stats.html
Things all mostly work.  Additional polish will be needed.
Need volunteers to test with multiple Seestars.
=> Re-worked Federation work.

front/app.py, front/public/main.js
Updated to latest planetary ephemeris (de440s.bsp over de421.bsp) and use JNOW rather than J2000.
Altered StellariumResource to request JSON instead of HTML for futureproofing and added retreiving of target name.
=> Small tweaks to search system

front/app.py, front/templates/clear_schedule.html, front/templates/mosaic_create.html, front/templates/nav.html, front/templates/schedule_list.html, front/templates/settings.html
1) Fixed issue with the Settings page not loading if all telescopes are offline.
2) Re-organized the Clear/Export/Import Schedule buttons in Schedule page
3) Converted Nav Bar to have a dropdown for all the subpages. 
4) Reformatted schedule list to include selected panels field and the federated split mosaic option
5) Removed a stray </div> from mosaic_create.html to correct formatting
=> SSC UI cleanup and re-organization

device/app.py, front/app.py
Add a front-end PUT command that will send SIGHUP to our own PID.
The device daemon will reload on that signal, picking up any new config changes.
=> Add a handler to reset the device daemon

device/app.py
Temporary workaround for SIGHUP on Windows.
=> Temporary workaround for SIGHUP on Windows

front/app.py, front/templates/command.html, front/templates/do_command.html
Updated formatting of the Commands Page
Fixed bug in startup sequence if lat or long are empty.
=> Updates to Command Page

.github/workflows/build_seestar_alp.yaml, front/app.py, front/templates/command.html, front/templates/do_command.html, front/templates/goto.html, front/templates/image.html, front/templates/index.html, front/templates/live.html, front/templates/live_mode.html, front/templates/mosaic.html, front/templates/schedule_base.html, front/templates/settings.html, front/templates/stats.html, front/templates/support.html, front/templates/system.html, raspberry_pi/setup.sh, raspberry_pi/systemd/seestar.service, raspberry_pi/update.sh
Revert the revert for at least the following PRs:
- Adding version code to the pages
- Making the support bundle platform agnostic
=> revert revert

device/config.py, device/config.toml.example, front/app.py, front/templates/config.html, front/templates/do_command.html, front/templates/nav.html
1) Fixed Navbar issues in commands page
2) Added SSC Config page to navbar - flagged experimental
3) Made confirmation dialog on the commands page configurable. Default is on.
=> Updates to commands page

front/app.py, front/templates/do_command.html
Parse the output of method sync and return some simplified output.
=> Created a parser for method sync

front/app.py, front/templates/do_command.html
Reverts smart-underworld/seestar_alp#291
=> Revert "Created a parser for method sync"

front/app.py
Added some resiliency to schedule import for malformed lines
Updated method_sync to return better information
=> Updates to command output

device/seestar_device.py, device/telescope.py
Added advanced features to start up sequence.
=> Kai start up sequence

front/public/AstroMosaicEngine.js, front/templates/partials/astro_mosaic.html, front/templates/partials/astrospheric.html, front/templates/planning.html
Big thinks to https://github.com/jarmoruuth/AstroMosaic/commits?author=jarmoruuth
for updating AstroMosaicEngine.js with the new embed features.
=> Planning Page: Added mosaic controls.

device/config.py
Also add some comments to document the object
=> Get logging levels from logging library

front/app.py, front/public/AstroMosaicEngine.js, front/templates/config.html, front/templates/partials/astro_mosaic.html, front/templates/partials/twilight_times.html, front/templates/planning.html
Fixed:
* Fix aladin css (done)
* Add feedback for failed search (done)
* local time vs UTC (done)
* Random other tweaks.
=> Planning Page Updates & Config page title.

device/seestar_imaging.py, front/public/liveview.js, front/templates/live.html, front/templates/live_base.html, front/templates/live_scenery.html, front/templates/live_star.html
Also, cleaned up some templates.  Put back double initial frame logic.
=> Switch live view screens dynamically when mode changes

front/templates/live_base.html, front/templates/live_moon.html, front/templates/live_planet.html, front/templates/live_sun.html, lib/__init__.py
The following modes were missing, broken, or not behaving as expected:
- sun
- moon
- planet
Additional, fixed a bug in Live View mode if you haven't specified a
mode previously.  (Mode was null.)
=> Fix live view modes

front/app.py, front/planning.json, front/templates/partials/astro_mosaic.html, front/templates/planning.html
* Added "Send to Schedule" to AsstroMosaic card.
* Added toggle cards off/on
* Cards now save their sate in front/planning.json
=> Planning Page Updates

front/app.py, front/public/main.js
Fix for issue #336.  Also changed retuened data to javascript to json format.
=> Fix for issue #336. 

front/templates/settings.html
Min,max allowed for exposure length.
=> Update to Settings

front/templates/settings.html
* used is VS ==
* fixed typo for exposure helper text
=> Settings page fixes

front/templates/eventstatus.html
=> Missed adding a file

device/config.py, device/config.toml.example, device/seestar_imaging.py, front/app.py, front/templates/live_status.html, front/templates/partials/live_card_status.html
- Add integration time to Live View
- Rename primary Elapsed Time to Time On Target
- Add save_frames, save_frames_dir to SSC Config screen
- Create save frames directory as needed
=> Live view time, config save frame

front/app.py
Fixed issue in method_sync if there are telescopes in config.toml that are configured, but offline.
=> Fixed exception in method_sync

front/templates/partials/astrospheric.html, front/templates/planning.html
* Only trigger if card is enabled and loaded.
=> Planning Page: Minor JS tweaks

front/app.py
Fix for error when importing from Stellarium and an unnamed star is selected.
=> Fix for error when importing from stellarium 

front/public/fit_import.js, front/templates/image_create.html
Added ability to pull Name, RA/DEC, Gain, Exposure length and LP filter status from previously created Seestar FIT files.
=> Pull details from previous seestar FIT file

.gitignore, front/app.py, front/public/main.js, front/templates/image_create.html, imaging/snr.py, requirements.txt
- Reworked the SNR function to hopefully be more representative.
- Added search for Minor planets (Asteroids).
- Added search for bright comets.
=> Rewrite of SNR function and new search abilities for minor planets and comets.

front/templates/goto_target.html, front/templates/mosaic_create.html
Quick patch to fix mosaic & goto pages with new lookup code.
=> Fixed a bug in mosaic & goto page with new lookup logic

device/config.py, front/app.py, front/templates/do_command.html, front/templates/schedule_list.html
Reverts smart-underworld/seestar_alp#370
This was not intended for main - reverting
=> Revert "Updates to SSC to support updated schedule code, start up sequence and below horizon"

front/app.py, front/public/main.js, front/templates/goto.html, front/templates/goto_target.html, front/templates/image.html, front/templates/image_create.html, front/templates/mosaic.html, front/templates/mosaic_create.html
- Added modal selectable list for comet searches that return more than one item.
- Added new search abilities to goto and mosaic.
- Cleaned up some of the HTML in goto, mosaic and image to remove spurious div and label tags along with header repetition.
=> Added new search abilities to goto and mosaic among other bits.

device/config.py, front/app.py, front/templates/do_command.html, front/templates/schedule_list.html
1) Updated config.py to add config item for is_EQ_mode
2) Updated app.py and do_command.html to add support for additional options to
start_up_sequence
3) Updated schedule_list.html to fix the stop/start scheduler button if
schedule state is complete
=> Updates for start_up_sequence and fixing the SSC schedule page

front/app.py, front/templates/do_command.html
Fixed typo and replaced missing javascript.
=> Fixed another typo

alpyca.failed_below_horizon.log, device/app.py, device/config.py, device/config.toml.example, device/seestar_device.py, device/seestar_federation.py, device/shr.py, device/telescope.py, front/app.py, front/templates/partials/schedule_state.html, front/templates/schedule_list.html
Major feature drop...
- transparently handles capture of targets in EQ mode below horizon
- fixes compass errors by taking into account of regional magnetic declination offsets. For example, to find the Moon or the Sun.
- Much improved run scheduler status feedback
- Allows for retry of target centering and goto for a target in a scheduled item
- one click full automation to be in full EQ mode, ready for imaging
- full support to edit an active schedule, to insert, delete or replace items in the schedule
- full support for federations scheduling, starting, stopping, schedule to a subset of devices in the federation.
- Quite a few performance improvements and code refactoring
Most of these are readily available in this release. Some features will be exposed once SSC is updated for end …
=> Major feature drop v2.2.0

scripts/SeeStarMove_v1.0.ps1, scripts/SeeStarObservations.html
If someone wants to integrate intoALP & SSC.  I'm happy to assist
=> Powershell script to move seestar files to your PC.

device/seestar_device.py
=> Update to seestar_device.py

front/app.py, front/templates/planning.html
- Added collapse toggle to planning page cards.
- Cards save their collapse state.
=> Planning page: collapse toggle

front/templates/index.html, front/templates/stats.html
- Added color coding Wi-Fi signal strength on stats page
- Added color coding Wi-Fi signal strength on index/home page
=> Wi-Fi signal strength color coding

front/templates/index.html, front/templates/stats.html
- Color coded free space on stats page
- Color coded free space on index/home page
=> Color coded free space

front/templates/index.html, front/templates/stats.html
- Color coded battery percent on stats page
- Color coded battery percent on index/home page
- Refactored logic for free storage color coding on stats page and index/home page.
Side note, not sure why the spacing on stats.html is so weird on github, it's not like that in VS Code.
=> Color coded battery percent

front/templates/nav.html
Make SSC Config not experimental
=> Make SSC Config not experimental

device/seestar_device.py
This allows the new firmware to move on to darks
=> Stop exposure as part of 3PPA completion

front/app.py, front/templates/schedule_list.html
If you use the shutdown command in the commands page, it was generating errors due to the Event Status panel.
=> Fixes in EventStatus

device/seestar_device.py
Plus some non-functional tweaks to code
=> Fix possible bug in start up thread

front/app.py, front/public/main.js, front/templates/goto_target.html, front/templates/image_create.html, front/templates/mosaic_create.html
Added Variable star search via online AAVSO database
Moved Simbad to be the default search on loading the page by request.
=> Added Variable star search via online AAVSO database

front/app.py
=> Use exposure duration for calculating int time

device/config.py, front/public/main.js
Implemented Adding / Deleting / Editing seestar devices from the SSC config page
=> Implemented Adding / Deleting / Editing seestar devices 

device/protocols/imager.py, device/seestar_imaging.py, front/public/liveview.js, front/templates/live_base.html, front/templates/live_moon.html, front/templates/live_star.html, front/templates/partials/live_controls.html, front/templates/partials/live_controls_exposure.html, front/templates/partials/live_controls_focus.html, root_app.py
Also:
- switch PNG to JPEG for video
- FIX: loading gif
=> Add exposure, focus controls to select live view modes

device/seestar_device.py, front/app.py, front/templates/partials/schedule_tab_header.html, front/templates/schedule.html, front/templates/schedule_list.html, front/templates/schedule_park.html, front/templates/schedule_startup.html
- Add startup sequence as a scheduled item
- Add scope_park as a scheduled item
- Rearrange schedule tabs to be more in line with a workflow of how you would use the scope
=> Add start-up sequence and scope_park as schedulable items

front/templates/support.html
Add cards for:
- Documentation
- Collaboration
- Feature Request / Bug Reporting
=> Support page rework

device/config.py
Fix for SSC config page goving 500 error when config.toml doesn't haee is_EQ_mode in seestar section
=> Fix for SSC config page goving 500 error

front/app.py, front/templates/nav.html, front/templates/platform_rpi.html
Add a platform menu on raspberry pi systems for service restart, and platform reboot/shutdown
=> Raspberry Pi platform menu

front/app.py
=> Fixed syntax error checking online status

docker/run.sh, front/app.py
Got a report that live view wasn't working in containers. This resolves the issue where the ip address was being resolved to a docker networking IP.
=> Fixup live view in containers

front/app.py, front/templates/go_online.html, front/templates/image_create.html
Replacing offline queue with federation device
=> First pass at removing the offline queue

.github/FUNDING.yml, device/config.py, device/config.toml.example, device/seestar_device.py, scripts/manual-mosaic.py
Fixup minor merge conflict in `manual-mosaic.py`
=> Merge main into SessionTimeRework

front/app.py
Force a json extension on export/download if it doesn't exist
=> Force a json extension on export/download if it doesn't exist

device/abstract_device.py, device/abstract_imager.py, device/seestar_remote.py, device/seestar_remote_imaging.py, front/templates/no_telescopes.html, lib/coordinates.py, lib/telescope_devices.py
New files to add initial remote functionality.
=> Add remote seestar and imager

device/seestar_device.py, device/seestar_remote.py, front/app.py
Fixup errors reported by the python linter
=> Address linting errors

.github/workflows/build_seestar_alp.yaml, front/app.py
This requires the user to unquarantine the unpacked directory via: 
```
xattr -r -d com.apple.quarantine ./seestar_alp
```
Additionally - I had some issues with SSL packaging and the pyinstaller code...such that I found it easier to just rewrite some of the check_internet_connection code
=> Add a mac binary download

front/app.py, front/templates/event_card.html
This will allow users to track the start_up_sequence until it's complete
=> Add Schedule Status to Commands Window

scripts/artificialhorizon.py
Creates an artificial horizon from Stellarium landscape (or could be modified to directly take a horizon.txt file) and tests if a given object is "within" the defined polygon
=> Example script for an artificial horizon test

device/abstract_device.py, device/seestar_device.py, device/seestar_federation.py, device/seestar_remote.py, device/telescope.py, front/app.py, front/templates/image_create.html, front/templates/mosaic_create.html, front/templates/partials/schedule_tab_header.html, front/templates/schedule.html, front/templates/schedule_exposure.html, front/templates/schedule_list.html
Added 'duplicate' as a valid value for federation_mode in mosiac & image schedule items
Added Exposure schedule item.
=> Updates to schedule

scripts/artificialhorizon.py
Added a test case from erewhon data; fixed edge case test; fixed typos
=> Artifical horizon

front/app.py, front/templates/schedule_exposure.html
and into ScheduleExposureResource to reduce calls to get_setting on every pageload.
=> Move get exposure out of _get_context 

device/event_callbacks.py, device/seestar_device.py, user_hooks/pi_status.conf.example
Additional minor typing, whitespace tweaks.
=> Switch hooks to use HOCOM syntax

device/seestar_device.py, device/telescope.py
Trigger events upon ALP actions.
Add wildcard support for events (event_*) and actions (action_*).
=> Add action events; add wildcards for event names

front/app.py, front/templates/live_moon.html, front/templates/live_solarsys.html, front/templates/live_sun.html, front/templates/partials/live_controls.html
Removing common "Goto" command which just worked for moon and moved to Moon, Sun, and "Solar Sys" templates
=> Refactoring Goto

front/app.py, lint/lint.sh
Fixup some linting problems reported in the front/app.py space.
=> Fixup errors reported by the linter

device/seestar_device.py
Fixes race conditions when we call `wait_end_op` after calling `send_message_param_sync`
=> race condition fixes

.gitignore, device/config.toml.example, device/seestar_device.py, device/telescope.py, front/app.py, front/templates/pa_refine.html
First update release to support the new ZWO Seestar firmware (2.47) that implemented native EQ mode.
=> Work with firmware2 47

device/protocols/imager.py, front/app.py, front/templates/live_status.html
Switch to mono fonts and also switch from milliseconds to seconds.
=> Fix live view formatting to be more stable

device/abstract_device.py, device/seestar_device.py, device/seestar_federation.py, device/telescope.py, front/app.py
- Add a lot of type annotations
- Add some new typed dictionaries
- Simplified some expressions
- Collapsed initializations into a single statement
=> Add typing, simplfying some logic

pyproject.toml, requirements.txt, requirements_full_overload.txt, schedule/__init__.py, uv.lock
- Add initial models to be used for refractoring / typing
- Bump dependencies
- Add "uv" support (optional)
=> Bump dependencies; add "uv" support; initial models

.github/workflows/lint.yaml
Add a github action that runs on:
- Push
- Opening/merging PRs
I'd like to make this action passing a requirement for merging - but this PR does not do that.
=> Add an action checking linting

.github/workflows/lint.yaml, device/config.py, device/discovery.py, device/exceptions.py, device/protocols/binary.py, device/seestar_device.py, device/seestar_logs.py, device/seestar_remote.py, device/shr.py, device/telescope.py, front/app.py, lint/lint.sh, lint/pylintrc, pyproject.toml, requirements.txt
Move to ruff linter
Fixup some of the errors with `ruff check --fix`
Fixup some of the errors by hand
Suppress some errors in `pyproject.toml`
=> Move to ruff linter

device/seestar_device.py, device/seestar_imaging.py, device/seestar_logs.py, device/seestar_remote.py, device/shr.py, device/telescope.py, device/test_geocoder.py, front/app.py, imaging/stretch.py, pyproject.toml
Drop 3 more ignored linting classes:
"E402",  # Module level import not at top of file
"E731",  # Do not assign a `lambda` expression, use a `def`
"F541",  # f-string without any placeholders
=> ruff fixes: Drop 3 more ignored linting classes

device/seestar_federation.py, front/app.py
There were no remove_schedule_item or insert_schedule_item_before routines on the seestar_federation class.
=> Insert and delete didn't work on schedule - federation page,

device/abstract_device.py, device/seestar_device.py, device/telescope.py, front/app.py, front/templates/schedule_base.html
After a schedule has been completed allow it to start over.
To do this:
Reset the current schedule item so that schedule will start over on first item
Reset of schedule will remove highlighted line in schedule
Redisplay the State and List areas of the screen
=> Allow schedule to start over after complete

front/app.py
Fixed issue with Dark Mode on Settings Page.
Added support for Continuous Shooting mode on Settings Page.
=> Settings Page Work

front/app.py, front/templates/do_command.html, front/templates/index.html, front/templates/stats.html
Added the ability to switch between Equitorial and Alt Azimith Mode on Commands Page
Added Mount Mode to Stats screens
Cleaned up Stats screens to only show non-empty values.
Re-worked get_device_state to leverage pydash.get to safely get values and handle empty/null values
Added support for "4x Mode" introduced in Seestar App 2.6.0 on Settings Page
=> Multiple Updates

.github/workflows/build_seestar_alp.yaml
Fixup builds:
- Use python 3.13
- Fix data/alp.dat inclusion
=> Fix workflow builds

front/templates/partials/astro_mosaic.html
Added Adjustable FOV for S50, S30 and S30 Pro.
Added support to reposition object within mosaic grid.
=> Updates to Mosaic section of planning page.
