docker/Dockerfile, docker/README.md, docker/run.sh, docker/util.sh
Docker containers set time zone to UTC by default - causes action-add_schedule_item_wait_until_time to fail unless local time zone is UTC.
This update allows user to set local time zone using an environment variable in run.sh.  (There may be slicker ways to do this that would not require user to modify run.sh)
Tested on Mac (Apple Silicon) only.
=> Added time zone support for docker container

docker/README.md, docker/entrypoint.sh, docker/run.sh, front/app.py
Update the docker setup to also launch the frontend flask UI, and make it available on port 5432
Also provide a mechanism to specify the timezone, without modifying code.
=> Expose the new frontend UI via docker

front/README.md, front/app.py, front/templates/base.html, front/templates/partials/schedule_state.html, front/templates/partials/schedule_tab_header.html, front/templates/schedule.html, front/templates/schedule_auto_focus.html, front/templates/schedule_base.html, front/templates/schedule_image.html, front/templates/schedule_list.html, front/templates/schedule_mosaic.html, front/templates/schedule_shutdown.html, front/templates/schedule_wait_for.html, front/templates/schedule_wait_until.html
- Tabs in the scheduler are now separate pages.  (Old implementation was Javascript-based, so redirects to a specific tab weren't working, and page reloads would always go back to the first tab.)
- Changed Scheduler toggle to use HTMX and also reflect that you're stopping or starting the scheduler (vs just "toggle")
=> Refactoring scheduler tabs into multiple pages; adding HTMX PoC

device/config.py, device/config.toml, docker/config.toml.example, front/app.py, front/templates/image_create.html
Front-end uses IP and new "uiport" entry in config.toml.
Refactored get_telescopes() to use "config" from seestar_alp.
=> Add configurable port for UI

front/public/main.js, front/templates/image.html, front/templates/mosaic.html
The stand alone image and mosaic screens also displayed the current schedule.  This could be confusing to the user.  Removed the schedule section from those screens. Also saw small bug in my code in app.py
=> Remove Schedule display on standalone imaging screens

front/app.py
On stats page was showing the default focus value.  Changing to use the current focus value which is likely more useful for people.
=> Show current focus instead of default focus val

device/config.py, device/config.toml, front/app.py, front/public/main.js, front/templates/base.html, front/templates/nav.html
This PR adds dark/light mode toggle for the WebUI (SSC).
All WebUI (SSC) configuration settings are moved to "webui_setting" in the config.toml.
Added uitheme under "webui_settings" in config.toml.
=> Add dark/light mode toggle to SSC.

device/config.toml, front/app.py, front/templates/command.html, front/templates/go_online.html, front/templates/image.html, front/templates/index.html, front/templates/mosaic.html, front/templates/schedule_list.html, front/templates/stats.html
Added new offline mode to front end.   If the seestar_alp API is not running, the web front end will switch to "offline" mode.  You create a schedule, and when the API is running, you can go online and all of the changes will be applied to the API.
Tested with one and two telescopes by @wileecyte and @erewhon in a variety of circumstances.
=> Offline mode for front end

front/app.py
Fixed config file location (using os.path) and fixed typo (toogle -> toggle) in toggle theme.
=> Fixed config file location and fixed typo in toggle theme

docker/Dockerfile.riscv64
This new file under docker/ is for building a container image to run on riscv64.
It includes a couple of build tools in the apt command (almost no python whl packages are pre-built for riscv so this is needed to build them), as well as uses a base container from canonical for ubuntu 22.04 but for riscv64.
On a riscv64 system, run on the git root "docker build . -f docker/Dockerfile.riscv64", and this has been executed to build this container: 
https://hub.docker.com/repository/docker/fede2/riscv64-seestar-alp/general
Now the s50 can be controller from this new cpu architecture, just like it is possible to do so on arm64 (raspberry pi).
=> Adding support for riscv64

front/app.py, requirements.txt
The free disk space inside the s50 is a bit hard to read if what you get is something like "3334". This change modifies the output from the telescope by adding the humanize library in order to print in gigabytes if the size is in this range, or in megabytes or other auto-ranged output.
MB 3334 is now shown as '35.0 GB'.
The value from the telescope has been *1024*1024 as the humanize function expects input in bytes.
requirements.txt has been modified to now install this python module.
=> Adding python-humanize for more clear disk space printing in frontend

raspberry_pi/setup_unified.sh
If config.toml doesn't exist when running setup_unified.sh, create it from example.
=> In setup_unified.sh, ensure config.toml exists

front/app.py
Fixed stack settings (converting to bool), also switched from eval to str2bool to make the code consistent. Temporary disabled factory_focal_pos as it will override focal_pos (in is also the case when using Bruno).
=> Fixed stack settings

device/config.py, device/config.toml.example, device/log.py, raspberry_pi/setup.sh, raspberry_pi/update.sh
controlled by a config value, that defaults to no subdir.
Fix setup.sh & update.sh to set this to "logs" like it used to be. 
NOTE - existing config.toml files will not be modified. If the user wants to put the logs in the log subdir, they can add the `log_prefix` entry.
=> Add ability to put logs in a subdir

device/app.py, device/config.py, front/app.py
Warn the user with ANSI decorated text colors when they launch without the top level root_app.py
Eg:
```
WARN
WARN: Deprecated app launch detected.
WARN: We recommend launching from the top level root_app.py, instead of ./device/app.py
WARN
```
=> Warn the user with ANSI decorated text colors when they launch without the top level root_app.py

root_app.py
Turns out Python 2.12 removed `pkg_resources`
This reverts this problematic change, and its fix for pyinstaller bundles
=> Revert PR#121 and PR#124

device/seestar_imaging.py, front/app.py
Used Typescript-type map definition syntax, which while syntacically correct in Python did not produce desired result. Broke display of offline schedules.
Also placeholder for new image module.
=> fixing offline schedule; boneheaded error <sigh>

raspberry_pi/setup.sh, raspberry_pi/update.sh
As discussed on the #seestar_alp-dev channel, [here](https://discord.com/channels/1204838310841815040/1263544341406683186/1273029827598880861) it isn't exactly clean having to specify `--break-system-packages`
This creates a pyenv install of python 3.12.5 (latest stable) - and makes a virtual env named `ssc-3.12.5`
All dependencies are installed into this virtual environment, rather than the system space.
The downside here, is that it does increase install time, since it has to build some of the python libraries.
=> Use virtual python environments in SSC

device/config.toml.example, device/rtspclient.py, device/seestar_device.py, device/seestar_imaging.py, device/telescope.py, front/app.py
FIX: resolved issue when ip_address isn't localhost (for example, 0.0.0.0 or hard coded to specific interface)
IMPROVE: streaming video would stall without being detected.  Now it should be more resilient.
Also some unused code cleanup.
=> Fixing non-localhost IP behavior, making live stream video more robust

device/seestar_device.py
Minor cleanup of the logging for socket errors. The thread name already includes the device name, we don't need to repeat it in the error log.
=> Remove repeated device name from socket error logging.

front/app.py
When enabling the LP filter, wait for filter wheel to complete the event. Much better than a hard coded wait. :)
=> Settings: Turning on LP filter redirects after it's complete.

front/app.py
Resolves #129.
Tested by exporting and getting the following results from the given input:
* `test` -> `test.csv`
* `test.csv` -> `test (1).csv` (since the first test.csv already existed, this was the expected result)
* `test.cs` -> `test.cs.csv` (just to show that, if the user makes a typo, the file will still export correctly, even if it looks weird)
=> Add CSV extension to export

raspberry_pi/update.sh
If we're already running the latest code - exit early.
=> Detect when running up-to-date code, and don't bring down the service

raspberry_pi/update.sh
Fixes error:
```
(ssc-3.12.5) bguthro@astro:~ $ ~/seestar_alp/raspberry_pi/update.sh
fatal: not a git repository (or any of the parent directories): .git
```
=> Fix executing the update.sh script from a working directory outside the repo

scripts/mosaic-stats.py
Add a script that analyzes a directory of mosaic panels, organized by panel id - and then calculates how many of each exposure time it contains - how much time is on each panel...and then recommends an order, and a duration for your next mosaic session, to catch all of the panels up to be equal with the panel that has the most time.
Eg:
```
Panel       30s    20s    10s    Hrs    DiffMins
Panel-11:    155    104    0    1.87    0.17
Panel-12:    147    52    0    1.51    21.5
Panel-13:    123    52    0    1.31    33.5
Panel-21:    144    101    0    1.76    6.67
Panel-22:    140    56    0    1.48    23.67
Panel-23:    113    56    0    1.25    37.17
Panel-31:    150    112    0    1.87    0.0
Panel-32:    139    48    0    1.43    26.83
Panel-33:    105    64    0    1.23    38.5 …
```
=> Add script for showing mosaic stats, and suggesting order & times

device/seestar_device.py, device/seestar_imaging.py, device/telescope.py, front/app.py, front/templates/live_status.html, front/templates/system.html, root_app.py
In certain situations, the API code will loop forever waiting for a
response from the Seestar.  (This can be caused the Seestar taking a
while to respond, then disconnecting the API.  As a result, the API
will just wait forever for a message that isn't going to be sent.)
- NEW: target name in Live View
- NEW: log message if response takes longer than 2 seconds to arrive
from Seestar (and every 2 seconds or so afterwards)
- NEW: use fixed IDs for select messages instead of an incrementing ID
- NEW: add last run time to internal threads
- NEW: system page that shows state of most app threads (have to
navigate to directly; not currently in nav)
=>  Fixed ID for select messages; thread telemetry

front/app.py
"rec_stablzn" is unavailable for firmware 3.11
=> Remove "rec_stablzn" from settings page.

front/app.py
to handle if multiple Seestars defined, but not all online.  Will now return Offline for any Seestars that are unavailable
=> Fixed method_sync 

device/seestar_device.py
The `send_message_param_sync()` function currently has a special case/check for if the JSON "method" is "pi_shutodwn". This PR corrects it to check for "pi_shutdown" instead.
=> Fix a minor typo in seestar_device.py

device/config.toml.example
to comment out the scope_aim_lat & scope_aim_lon settings under the seestars section. Added a comment indicating these values can be used to override the default on a per-device basis.
=> Updated config.toml.example 

.github/workflows/build_seestar_alp.yaml
Allow non-tagged artifact generation, named like:
`SeeStarAlp-linux-v2.1.0-206-gd377cea.zip`
`SeeStarAlp-windows-v2.1.0-206-gd377cea.zip`
This can be triggered manually, whenever we want to cut a release via the Actions tab.
Additionally, this can also be triggered from the github cli.
Eg:
```
gh workflow --repo bguthro/seestar_alp run build_seestar_alp.yaml --ref bguthro/gh-actions-version
```
Once merged, we'd ideally release from the main `smart-underworld/seestar_alp` repo, rather than a personal fork.
=> Actions re-work for non-tagged artifact generation

front/app.py
I noticed a couple typos in the SSC settings descriptions. This PR fixes them.
=> A few minor spelling/typo fixes

front/app.py, front/templates/support.html
Allow for support bundles without seestar logs - both when the user requests it, and when the scope is offline
=> Allow for support bundles without seestar logs

device/protocols/binary.py
Address errors when scope goes offline, and then comes back.
This would flood logs with lines like:
```
2024-12-10T14:46:56.034 ERROR SocketHeartbeatMessageThread.Seestar Alpha Send Socket error: [Errno 32] Broken pipe
```
=> Handle EPIPE

front/app.py, front/templates/clear_schedule.html
Upload allows the upload & import of a schedule from the client accessing ALP.
Download allows the download of the current schedule in ALP to the client.
Import will import a schedule from the filesystem of the system ALP is running on.
Export will export a schedule to the filesystem of the system ALP is running on.
=> Added Upload/Download functionality for schedule import/export

front/app.py, front/templates/image_create.html, front/templates/mosaic_create.html
Added tweak to do_action_device to pass {} if no params are provided.
=> Use gain from config.toml by default in image/mosaic forms

scripts/support-bundle.py
This script can be run with, or without SSC/ALP running, so we can help users debug issues.
=> Add a script to get the support bundle contents, even when SSC isn't running

front/app.py
When adding an exposure schedule item, it will now pull the current value of exposure, if available, otherwise the config.toml default will be used.
=> Adaptively select exposure value

device/event_callbacks.py, device/seestar_device.py, user_hooks/goto.json.example
This adds an event callback framework, to initially take action on events sent from the seestar - but could be extended for timing based events, or other purposes.
The intent is for it to be lightweight, and reactionary to the events already being sent from the seestar.
I do add an additional `get_device_state` at init time.
=> Initial event callback framework, with two examples

front/app.py, front/templates/do_startup.html, front/templates/partials/schedule_list.html
Created seconds_to_hms function that can be used in Jinja templates to convert seconds to HH:MM:SS
Updated Startup page to have a Stop button for the Startup Sequence. Fixed bug in _get_context_real where stack_state was not getting passed Fixed bug in _get_context_real where exposure was not properly being converted to seconds
Changed schedule_list.html to use seconds_to_hms
General formatting improvements to the extended schedule item info.
=> Schedule Page Bugfixes and Tweaks

front/app.py, front/templates/live_base.html
The following screens when blank or had an error when no scopes were turned on.  This was generally due to the code discovering an error or null value and doing a 'return' without displaying the screen.  What i did was put empty values in the needed variables and let the screen display.
Goto 
Command
LIve
Startup
Guest Mode
=> Fix Page Trasition errors when no scopes turned on.

device/config.py, device/config.toml.example, front/app.py, front/templates/base.html, simulator/requirements.txt
Allow the user to change the color scheme of SSC, along with the fonts used.
Example config changes that allow the user to customize their theme:
```
text_color = "darkred"
font_family = "Orbitron"
font_url = "https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap"
link_color = "red"
accent_color = "darkred"
```
```
text_color = "green"
font_family = "Kode Mono"
font_url = "https://fonts.googleapis.com/css2?family=Kode+Mono:wght@400..700&display=swap"
link_color = "darkgreen"
accent_color = "darkgreen"
```
=> Allow the user to customize colors and fonts
